Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

from myblog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('myblog/', include('myblog.urls')),
]

Blog/myblog/urls.py
from django.urls import path
from . import views


app_name = 'myblog'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_regist, name='register'),
    path('<str:username>/', views.user_index, name='userindex'),
    path('<str:username>/blogs/', views.user_blogs, name='userblogs'),
    path('<str:username>/blogs/posts/', views.user_posts, name='userposts'),
    path('<str:username>/blogs/drafts/', views.user_drafts, name='userdrafts'),
    path('<str:username>/blogs/newblog/', views.user_newblog, name='newblog'),
    path('<str:username>/logout/', views.user_logout, name='userlogout'),
    path('blogs/detail/<int:id>/', views.blog_detail, name='blogdetail'),
]

Blog/myblog/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class User(models.Model):
    status_choice = ((0, '离线'),
                     (1, '在线'))

    username = models.CharField(max_length=68, unique=True, verbose_name='用户名')
    email = models.EmailField(verbose_name='邮箱')
    password = models.CharField(max_length=568, verbose_name='登录密码')
    re_time = models.DateTimeField(default=timezone.now, verbose_name='注册时间')
    status = models.SmallIntegerField(choices=status_choice, default=0, verbose_name='用户状态')

    def __str__(self):
        return self.username

    class Meta:
        ordering = ['-re_time',]
        verbose_name = '用户'
        verbose_name_plural='用户'


class Blog(models.Model):
    status_choice = ((0, '发表'),
                     (1, '草稿'))

    title = models.CharField(max_length=100, verbose_name='标题')
    status = models.SmallIntegerField(choices=status_choice, default=1, verbose_name='博客状态')
    author = models.ForeignKey('User', on_delete=models.CASCADE, verbose_name='作者', related_name='blog_post')
    # body = models.ForeignKey('Content', null=True, blank=True, on_delete=models.CASCADE, verbose_name='博文', related_name='blog_body')
    body = models.TextField(verbose_name='博文', null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    publish_time = models.DateTimeField(default=timezone.now, verbose_name='发表时间', null=True, blank=True)
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publish_time',]
        verbose_name = '博客'
        verbose_name_plural = '博客'


class Content(models.Model):
    blog_id = models.OneToOneField('Blog', on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        blog = Blog.objects.get(pk=self.blog_id)
        return blog.title

    class Meta:
        ordering = ['blog_id',]
        verbose_name = '博文'
        verbose_name_plural = '博文'

class Comment(models.Model):
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE, verbose_name='博客')
    comment_by = models.ForeignKey('User', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='评论者')
    publish_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    comment_text = models.TextField(verbose_name='评论详情')

    class Meta:
        ordering = ['-publish_time']
        verbose_name = '评论'
        verbose_name_plural = '评论'

    def __str__(self):
        return 'comment by {} on {}'.format(self.comment_by, self.blog)

Blog/myblog/forms.py
from django import forms
from .models import User, Blog

class LoginForm(forms.Form):
    username = forms.CharField(max_length=68, label='', widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password = forms.CharField( max_length=256, label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))



class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=256, label='输入密码', widget=forms.PasswordInput(attrs={'placeholder': 'Input Password'}))
    password2 = forms.CharField(max_length=256, label='确认密码', widget=forms.PasswordInput(attrs={'placeholder': 'Repeat Password'}))

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('两个密码不匹配！')
        return cd['password2']


    class Meta:
        model = User
        fields = ('username','email')
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email'})
        }
        labels = {
            'username': '用户名',
            'email': '邮箱地址'
        }


class NewBlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'body')

        labels = {
            'title': '标题',
            'body': '正文'
        }
        widgets = {
            'body': forms.TextInput()
        }

Blog/myblog/views.py
from django.shortcuts import render, HttpResponse,redirect
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
import hashlib

from .models import User, Blog, Comment
from .forms import LoginForm, RegisterForm

# Create your views here.

def hash_code(s, salt='saltps'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()

def user_login(request):
    if request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('myblog:userindex', args=(request.session['user_name'],)))
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd.get('username', None)
            password = cd.get('password', None)
            try:
                user_obj = User.objects.get(username=username)
            except User.DoesNotExist:
                warning = '用户不存在！'
                return render(request, 'myblog/login.html', {'form':form, 'warning':warning})
            if user_obj:
                if user_obj.password == hash_code(password):

                    #允许登录
                    user_obj.status = 1
                    user_obj.save()
                    request.session['is_login'] = True
                    request.session['user_id'] = user_obj.id
                    request.session['user_name'] = user_obj.username

                    blogs_obj = Blog.objects.filter(status=0).order_by('-publish_time')
                    blogs = list()
                    for blog in blogs_obj:
                        blogs.append({'title': blog.title, 'id': blog.id})
                    redirect(reverse('myblog:userindex', args=(user_obj.username,)))
                    return render(request, 'myblog/userindex.html', {'username': username,'blogs': blogs})
                else:
                    warning = '密码不正确！'
                    return render(request, 'myblog/login.html', {'form':form,'warning':warning})
        else:
            warning = '请检查输入数据！'
            return render(request, 'myblog/login.html', {'form':form,'warning':warning})
    else:
        form = LoginForm()
    return render(request, 'myblog/login.html', {'form':form})


def user_regist(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            username = cd['username']
            try:
                user_obj = User.objects.get(username=username)
                if user_obj:
                    warning = '用户名已被注册！'
                    return render(request, 'myblog/register.html', {'form':form,'warning':warning})
            except User.DoesNotExist:
                password = hash_code(cd['password1'])
                email = cd['email']
                new_user = User(username=username, email=email, password=password, re_time=timezone.now())
                new_user.save()
                message = '注册成功！'
                return render(request, 'myblog/register.html', {'message': message})
        else:
            warning = '请检查输入数据！'
            return render(request, 'myblog/register.html', {'form':form,'warning':warning})
    else:
        form = RegisterForm()
    return render(request, 'myblog/register.html', {'form': form})


def user_index(request, username):
    return render(request, 'myblog/userindex.html', {'username': username})

def user_logout(request, username):
    if request.session.get('is_login', None):
        print('logout................')
        user_obj = User.objects.get(username=username)
        user_obj.status = 0
        user_obj.save()

        request.session.flush()
        return HttpResponseRedirect(reverse('myblog:login'))

    return HttpResponseRedirect(reverse('myblog:login'))


def user_blogs(request, username):
    if request.method == 'GET':
        try:
            user_obj = User.objects.get(username=username)
            return render(request, 'myblog/blogs.html', {'username': username})
        except User.DoesNotExist:
            return HttpResponse('用户不存在')



def user_posts(request, username):
    blogs = Blog.objects.filter(author__username=username, status=0)
    blogs_title = list()
    for blog in blogs:
        blogs_title.append({'id':blog.id, 'title':blog.title})

    return render(request, 'myblog/posts.html', {'blogs': blogs_title, 'username': username})


def user_newblog(request, username):
    if request.method == 'GET':
        return render(request, 'myblog/newblog1.html', {'username': username})
    elif request.method == 'POST':
        title = request.POST['title']
        body = request.POST['body']
        status = request.POST.get('status', 0)
        print(title, body, status)

        newblog = Blog()
        newblog.title = title
        newblog.body = body
        newblog.status = status
        newblog.created_time = timezone.now()
        newblog.publish_time = timezone.now()
        try:
            author = User.objects.get(username=username)
            newblog.author = author
        except User.DoesNotExist:
            return HttpResponse('用户不存在')
        newblog.save()
        if not status:
            message = '发表成功！'
        return render(request, 'myblog/newblog1.html', {'message': message})


def user_drafts(request, username):
    blogs = Blog.objects.filter(author__username=username, status=1)
    blogs_title = list()
    for blog in blogs:
        blogs_title.append({'id': blog.id, 'title': blog.title})

    return render(request, 'myblog/drafts.html', {'blogs': blogs_title, 'username': username})


def blog_detail(request, id):
    if request.method == 'GET':
        try:
            blog = Blog.objects.get(pk=id)
            comments = list()
            comments_obj = Comment.objects.filter(blog__pk=id)[:3]
            for comment in comments_obj:
                comments.append('{}: {}'.format(comment.comment_by, comment.comment_text))
            print(comments)
            print('^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^')
            return render(request, 'myblog/detail.html', {'title': blog.title,
                                                          'author': blog.author.username,
                                                          'publish_time': blog.publish_time,
                                                          'body': blog.body,
                                                          'status': blog.status,
                                                          'id': id,
                                                          'comments': comments})
        except Blog.DoesNotExist:
            message = '你要找的博文已经没有啦！'
            return render(request, 'myblog/detail.html', {'message': message, 'id': id,})
        except Exception:
            message = '发生了一点意外哟！'
            return render(request, 'myblog/detail.html', {'message': message, 'id': id,})
    elif request.method == 'POST':
        comment_by_id = request.session.get('user_id', None)
        if comment_by_id:
            comment_text = request.POST.get('comment_body', None)
            if comment_text:
                comment = Comment()
                comment.blog = Blog.objects.get(pk=request.POST['blog_id'])
                comment.comment_by = User.objects.get(pk=comment_by_id)
                comment.comment_text = comment_text
                comment.publish_time = timezone.now()
                comment.save()
                return render(request, 'myblog/detail.html', {'comment': comment_text,
                                                              'comment_by': comment.comment_by.username,
                                                              'id': request.POST['blog_id']
                                                              })
            else:
                return HttpResponse('评论内容不可为空！')
        else:
            return HttpResponse('请先登录!')


def index(request):
    try:
        blogs_obj = Blog.objects.filter(status=0).order_by('-publish_time')
        blogs = list()
        for blog in blogs_obj:
            blogs.append({'title': blog.title, 'id':blog.id})
        return render(request, 'myblog/index.html', {'blogs': blogs})
    except:
        message = 'No data'
        return render(request, 'myblog/index.html', {'message':message})

Blog/myblog/templates/myblog/blogs.html
{% extends 'base.html' %}

{% block title %}
    {{ username }}的博客
{% endblock %}

{% block logo %}
    {{ username }}的博客
{% endblock %}

{% block tool%}
    <a class="linktext" href="{% url 'myblog:userblogs' username %}">我的博客</a>
    <a class="linktext" href="{% url 'myblog:userlogout' username %}">退出</a>
{% endblock %}

{% block content %}
    <ul id="listtext">
        <li><a class="linktext" href="{% url 'myblog:userposts' username %}">已发博文</a></li>
        <li><a class="linktext" href="{% url 'myblog:userdrafts' username %}">草稿箱</a></li>
        <li><a class="linktext" href="{% url 'myblog:newblog' username %}">新建博文</a></li>
    </ul>
{% endblock %}

Blog/myblog/templates/myblog/detail.html
{% extends 'base.html' %}

{% block title %}
    {% if message %}
        错误提示
    {% else %}
         {{ title }}--{{ author }}的博客
    {% endif %}
{% endblock %}

{% if message %}
    {% block logo %}
        {{ message }}
    {% endblock %}
{% else %}
    {% block content %}
        <br/>
        <div id="blog-detail">
            <div><span id="blog-title">{{ title }}</span></div>
            <div>
                <span id="blog-author">作者：{{ author }}</span>
                <span id="blog-time"> 发表时间：{{ publish_time }}</span>
            </div>
            <br/>
            <div id="blog-body"><span style="word-break:break-all">{{ body }}</span></div>
        </div>

        {% if not status %}
            <div id="comment-detail">
                <script>
                    function commit_comment(){
                        var form = new FormData(document.getElementById("comment_form"));
                        var flag = true;
                        var comment;
                        for(var pair of form.entries()){
                        if(flag){
                        flag = false;
                        continue;}

                        comment = pair[1];
                        break;
                        }
                        console.log("我"+": "+comment)
                       fetch("{% url 'myblog:blogdetail' id %}", {
                               method: "POST",
                               body: form}).then(document.getElementById("new_comment").innerHTML = "我" + ": " + comment)
                    }
                </script>

                <p>评论列表</p>
                {% for comment in comments %}
                    <p>{{ comment }}</p>
                {% endfor %}
                <form id="comment_form">
                    {% csrf_token %}
                    <input type="text" name="comment_body" id="comment_text">
                    <input type="hidden" name="blog_id" value="{{ id }}">
                    <input type="button" value="提交" onclick="commit_comment()">
                </form>
                <p id="new_comment"></p>
            </div>
        {% endif %}

    {% endblock %}

{% endif %}

Blog/myblog/templates/myblog/drafts.html
{% extends 'base.html' %}

{% block title %}
    {{ username }}的草稿箱
{% endblock %}

{% block logo %}
    {{ username }}的草稿箱
{% endblock %}

{% block tool%}
    <a class="linktext" href="{% url 'myblog:userblogs' username %}">我的博客</a>
    <a class="linktext" href="{% url 'myblog:userlogout' username %}">退出</a>
{% endblock %}

{% block content %}
    <ul id="listtext">
        {% for blog in blogs %}
            <li><a class="linktext" href="{% url 'myblog:blogdetail' blog.id %}" target="_blank">{{ blog.title }}</a> </li>
        {% endfor%}
    </ul>

{% endblock %}

Blog/myblog/templates/myblog/index.html
{% extends 'base.html' %}
<meta http-equiv="Refresh" content="url 'myblog:login'">
{% load static %}

{% block title %}
首页
{% endblock %}

{% block logo %}
首页
{% endblock %}

{% block tool %}
    <a class="linktext" href="{% url 'myblog:login' %}">登录</a>
{% endblock %}

{% block content %}
{% if message %}
    <h4 style="color: #FFBF00; margin-left: 160px;">{{ message }}</h4>
{% else %}
     <ul id="listtext">
        {% for blog in blogs %}
            <li>
                <a class="linktext" href="{% url 'myblog:blogdetail' blog.id %}" target="_blank">{{ blog.title }}</a>
            </li>
        {% endfor%}
    </ul>
{% endif %}
{% endblock %}

Blog/myblog/templates/myblog/login.html
{% extends "base.html" %}

<meta http-equiv="Refresh" content="url 'myblog:register'">
{% block title %}Log-in{% endblock %}

{% block logo %}My-Blog{% endblock %}

{% block content %}
<div id="loginform">
    <div id="loginformtext">
        <h2>欢迎登录</h2>
        <form action="{% url 'myblog:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="登录"></p>
            {% if warning %}
            <div id="warning"><p> {{ warning }}</p></div>
            {% endif %}
        </form>
        <p>没有账号？<a href="{% url 'myblog:register' %}">点我注册</a></p>
    </div>
</div>
{% endblock %}

Blog/myblog/templates/myblog/newblog.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    创建博文
{% endblock %}



{% block content %}
    <br/>
    <div class="editor">
        <script id="container" class="editor-content" name="content" type="text/plain">test</script>
    </div>


    <div>

        <form action="{% url 'myblog:newblog' username %}" method="post">
            {% csrf_token %}
            <input type="hidden" id="blog_body" name="body">
            <script type="text/javascript" src="{% static 'js/ueditor/ueditor.config.js' %}"></script>
            <script type="text/javascript" src="{% static 'js/ueditor/ueditor.all.js' %}"></script>
            <script type="text/javascript">
                var ue = UE.getEditor('container',);
                ue.ready(function(){
                    var txt = ue.getContentTxt();
                    document.getElementById("blog_body").value = txt
                });

            </script>
            <input type="submit" value="立即发表">
        </form>
    </div>



{% endblock %}

Blog/myblog/templates/myblog/newblog1.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    创建博文
{% endblock %}

{% block content %}
{% if message %}
    <h4>{{ message }}</h4>
{% else %}

<script>
    function keepdraft(){
        var form = new FormData(document.getElementById("blog_edit"));
        form.append('status', '1')

        fetch("{% url 'myblog:newblog' username %}", {
            method: "POST",
            body: form
        }).then(alert("保存成功！"))
    }
</script>

<form action="{% url 'myblog:newblog' username %}" method="post" class="edit_blog" id="blog_edit">
    {% csrf_token %}
    <div>
        <p><label>标题：</label></p>
        <p><input type="text" maxlength="100" style="width:78%" name="title" id="publish_title" required></p>
    </div>
    <div>
        <p><label>正文：</label></p>
        <p><textarea name="body" rows="30" cols="150" id="publish_body" ></textarea></p>
    </div>
    <input type="submit" value="立即发表">&nbsp;<input type="button" value="保存草稿" onclick="keepdraft()">
</form>


{% endif %}

{% endblock %}

Blog/myblog/templates/myblog/posts.html
{% extends 'base.html' %}

{% block title %}
    {{ username }}的博文
{% endblock %}

{% block logo %}
    {{ username }}的博文
{% endblock %}

{% block tool%}
    <a class="linktext" href="{% url 'myblog:userblogs' username %}">我的博客</a>
    <a class="linktext" href="{% url 'myblog:userlogout' username %}">退出</a>
{% endblock %}

{% block content %}
    <ul id="listtext">
        {% for blog in blogs %}
            <li><a class="linktext" href="{% url 'myblog:blogdetail' blog.id %}" target="_blank">{{ blog.title }}</a> </li>
        {% endfor%}
    </ul>

{% endblock %}

Blog/myblog/templates/myblog/register.html
{% extends "base.html" %}
<meta http-equiv="Refresh" content="url 'myblog:login'">
{% block title %}Register{% endblock %}

{% block logo %}My-Blog{% endblock %}

{% block content %}

{% if message %}
    <div>
        <h4>{{ message }}<a href="{% url 'myblog:login' %}">点我登录</a> </h4>
    </div>
{% elif message == None %}
    <div id="loginform">
        <div id="loginformtext">
            <h2>欢迎注册</h2>
            <form action="{% url 'myblog:register' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <p><input type="submit" value="注册"></p>
                {% if warning %}
                    <div id="warning"><p> {{ warning }}</p></div>
                {% endif %}
            </form>
            <p>已有账号？<a href="{% url 'myblog:login' %}">点我登录</a></p>
        </div>
    </div>
{% endif %}

{% endblock %}

Blog/myblog/templates/myblog/userindex.html
{% extends 'base.html' %}

{% block title %}
    {{ username }}的主页
{% endblock %}

{% block logo %}
    {{ username }}的主页
{% endblock %}

{% block tool%}
    <a class="linktext" href="{% url 'myblog:userblogs' username %}">我的博客</a>
    <a class="linktext" href="{% url 'myblog:userlogout' username %}">退出</a>
{% endblock %}

{% block content %}

    <ul id="listtext">
        <h5>热门博文</h5>
        {% for blog in blogs %}
            <li><a class="linktext" href="{% url 'myblog:blogdetail' blog.id %}" target="_blank">{{ blog.title }}</a> </li>
        {% endfor%}
    </ul>
{% endblock %}